export const REFRESH_POSTS_REQUESTED = 'connection/REFRESH_POSTS_REQUESTED';
export const REFRESH_POSTS_FAILED = 'connection/REFRESH_POSTS_FAILED';
export const REFRESH_POSTS_SUCCEED = 'connection/REFRESH_POSTS_SUCCEED';

export const REFRESH_CATEGORIES_REQUESTED = 'connection/REFRESH_CATEGORIES_REQUESTED';
export const REFRESH_CATEGORIES_FAILED = 'connection/REFRESH_CATEGORIES_FAILED';
export const REFRESH_CATEGORIES_SUCCEED = 'connection/REFRESH_CATEGORIES_SUCCEED';

export const POST_PARAMS_CHANGED = 'connection/POST_PARAMS_CHANGED';
