export const REFRESH_POSTS_REQUESTED = 'connection/REFRESH_POSTS_REQUESTED';
export const REFRESH_POSTS_FAILED = 'connection/REFRESH_POSTS_FAILED';
export const REFRESH_POSTS_SUCCEED = 'connection/REFRESH_POSTS_SUCCEED';

export const REFRESH_CATEGORIES_REQUESTED = 'connection/REFRESH_CATEGORIES_REQUESTED';
export const REFRESH_CATEGORIES_FAILED = 'connection/REFRESH_CATEGORIES_FAILED';
export const REFRESH_CATEGORIES_SUCCEED = 'connection/REFRESH_CATEGORIES_SUCCEED';

export const NEW_CATEGORY_SELECTED = 'connection/NEW_CATEGORY_SELECTED';
